---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluentd-reloader
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-reloader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluentd-reloader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fluentd-reloader
subjects:
  - kind: ServiceAccount
    name: fluentd-reloader
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fluentd-reloader
spec:
  schedule: "0 3 * * *" # every day at 3:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: fluentd-reloader
          restartPolicy: Never
          containers:
            - name: fluentd-reloader
              imagePullPolicy: Always
              image: donchev7/fluentd-reloader
              env:
                - name: FLUENTD_NAMESPACE
                  value: "logging"
                - name: FLUENTD_SERVICE_URL
                  value: "logging.donchev.is"
                - name: FLUENTD_CERT_NAME
                  value: "fluentd-tls"
